      - name: Run Data Preprocessing
        run: |
          python scripts/02_preprocess_data.py

      - name: Upload Processed Data Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processed-cancer-data        #
          path: processed_data/              
          retention-days: 7                   